name: cinemacuenca
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
